### ISSUE TITLE
Coco2Voc convert crashes

### ISSUE THREAD

**Issue by TheMinecraftOverlordYT** [nipdep/imgann#2]
When calling
` Convertor.coco2voc( <image dataset dir> : string, <coco annotated .json file dir> : string, <voc formatted .xml file saving folder dir> : string, <center COCO> : bool= True)`
The process exits. This is because coco2voc() invokes coco.extract(), but doesn't pass in the `center` parameter.

Additionally, the process exits when it encounters a file without a bbox attribute. I propose to simply log the error and skip past it without adding it to the list of files to convert.

**Comment by nipdep** [comment]
that issue is resolve in the latest version of imgann.
and thank for inform the issue.
