### ISSUE TITLE
add coco to yolo and voc to yolo examples

### ISSUE THREAD

**Issue by Mahmood-Hussain** [nipdep/imgann#5]
Hi,
This is nice work please add examples of newly added supported conversions. For me voctoyolo was useful but there was no example although it was easy to find programmers are lazy so please consider adding it.

**Comment by nipdep** [comment]
Here:  https://imgann.readthedocs.io/en/latest/api.html#voc2yolo \
in the [readthedocs](https://imgann.readthedocs.io/en/latest/index.html).
